# Generated by Django 3.0.7 on 2021-04-18 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='limit',
            field=models.IntegerField(default=10, verbose_name='借阅上限'),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='图书ID'),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.CIP', verbose_name='图书ISBN编号'),
        ),
        migrations.AlterField(
            model_name='books',
            name='place',
            field=models.CharField(choices=[('0', '图书流通室'), ('1', '图书阅览室')], default='图书流通室', max_length=10, verbose_name='存放位置'),
        ),
        migrations.AlterField(
            model_name='books',
            name='state',
            field=models.CharField(choices=[('0', '已借出'), ('1', '不外借'), ('2', '未借出'), ('3', '已预约')], default='未借出', max_length=10, verbose_name='图书状态'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Books', verbose_name='图书ID'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='借阅日期'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='due',
            field=models.DateField(verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Reader', verbose_name='读者ID'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='restore',
            field=models.DateField(null=True, verbose_name='实际归还时间'),
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='status',
            field=models.CharField(choices=[('0', '未完成'), ('1', '已完成')], default='未完成', max_length=5, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='author',
            field=models.CharField(max_length=50, verbose_name='图书作者'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='图书ISBN编号'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='pdate',
            field=models.DateTimeField(verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='rest',
            field=models.IntegerField(verbose_name='剩余数量'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='title',
            field=models.CharField(max_length=100, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='total',
            field=models.IntegerField(verbose_name='总数量'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='borrow',
            field=models.IntegerField(default=0, verbose_name='已借阅数量'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=30, verbose_name='读者姓名'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='due',
            field=models.DateField(verbose_name='失效日期'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.CIP', verbose_name='图书ISBN编号'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Reader', verbose_name='读者ID'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('0', '未完成'), ('1', '已完成')], default='未完成', max_length=5, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='读者ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=256, verbose_name='读者密码'),
        ),
    ]
