# Generated by Django 3.2 on 2021-05-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20210511_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cip',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='cip',
            name='total',
        ),
        migrations.AlterField(
            model_name='cip',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='出版社'),
        ),
    ]
