# Generated by Django 3.2 on 2021-05-18 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='图书ID')),
                ('place', models.CharField(choices=[('0', '图书流通室'), ('1', '图书阅览室')], default='图书流通室', max_length=10, verbose_name='存放位置')),
                ('state', models.CharField(choices=[('0', '已借出'), ('1', '不外借'), ('2', '未借出'), ('3', '已预约')], default='未借出', max_length=10, verbose_name='图书状态')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '图书管理',
                'verbose_name_plural': '图书管理',
            },
        ),
        migrations.CreateModel(
            name='Bookslips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='借阅日期')),
                ('due', models.DateField(verbose_name='截止日期')),
                ('restore', models.DateField(null=True, verbose_name='实际归还时间')),
                ('status', models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '已通知')], default='未完成', max_length=5, verbose_name='当前状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.books', verbose_name='图书ID')),
            ],
            options={
                'verbose_name': '借阅管理',
                'verbose_name_plural': '借阅管理',
            },
        ),
        migrations.CreateModel(
            name='CIP',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='图书ISBN编号')),
                ('title', models.CharField(max_length=100, verbose_name='图书名称')),
                ('author', models.CharField(max_length=50, verbose_name='图书作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('pdate', models.DateTimeField(verbose_name='出版时间')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': 'CIP管理',
                'verbose_name_plural': 'CIP管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='读者ID')),
                ('pwd', models.CharField(max_length=256, verbose_name='读者密码')),
            ],
            options={
                'verbose_name': '账号管理',
                'verbose_name_plural': '账号管理',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='libapp.user')),
                ('name', models.CharField(max_length=30, verbose_name='读者姓名')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('limit', models.IntegerField(default=10, verbose_name='借阅上限')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '读者管理',
                'verbose_name_plural': '读者管理',
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='产生时间')),
                ('money', models.IntegerField(verbose_name='金额')),
                ('status', models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '已通知')], default='未完成', max_length=5, verbose_name='支付状态')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.bookslips', verbose_name='关联的借阅记录')),
            ],
            options={
                'verbose_name': '罚金管理',
                'verbose_name_plural': '罚金管理',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.cip', verbose_name='图书ISBN编号'),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='预约日期')),
                ('due', models.DateField(verbose_name='失效日期')),
                ('status', models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '已通知')], default='未完成', max_length=5, verbose_name='预约状态')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.cip', verbose_name='图书ISBN编号')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.reader', verbose_name='读者ID')),
            ],
            options={
                'verbose_name': '预约管理',
                'verbose_name_plural': '预约管理',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='bookslips',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.reader', verbose_name='读者ID'),
        ),
        migrations.CreateModel(
            name='Bookcollections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', '未收藏'), ('1', '已收藏')], default='未收藏', max_length=5, verbose_name='当前状态')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.cip', verbose_name='图书ISBN编号')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.reader', verbose_name='读者ID')),
            ],
            options={
                'verbose_name': '收藏管理',
                'verbose_name_plural': '收藏管理',
            },
        ),
    ]
