# Generated by Django 3.2 on 2021-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcollections',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookslips',
            name='status',
            field=models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '已通知')], default='0', max_length=5, verbose_name='当前状态'),
        ),
    ]
