# Generated by Django 3.2 on 2021-05-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20210527_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', '未完成'), ('1', '已完成'), ('2', '已通知')], default='未完成', max_length=5, verbose_name='状态')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.cip', verbose_name='图书ISBN编号')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.reader', verbose_name='读者ID')),
            ],
        ),
    ]
