# Generated by Django 3.2 on 2021-05-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_bookcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslips',
            name='restore',
            field=models.DateField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
    ]
