# Generated by Django 3.2 on 2021-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_alter_bookslips_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='money',
            field=models.IntegerField(default=0, verbose_name='金额'),
        ),
    ]
